controller_frequency: 10.0
TrajectoryPlannerROS:
  max_vel_x: 0.6
  min_vel_x: 0.35
  max_vel_theta: 0.85
  min_in_place_vel_theta: 0.45

  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  holonomic_robot: true