
  obstacle_range: 1.5
  raytrace_range: 2
  footprint: [[0.17, 0.2], [0.17, -0.2], [-0.17,-0.2], [-0.17, 0.2]]
#robot_radius: ir_of_robot
  inflation_radius: 0.15
  max_obstacle_height: 1
  min_obstacle_height: 0.0
  observation_sources: scan 

  scan: {sensor_frame: lidar_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

