obstacle_range: 0.5
raytrace_range: 0.5
footprint: [[0.15, 0.2], [0.15, -0.2], [-0.15,-0.2], [-0.15, 0.2]]
#robot_radius: ir_of_robot
inflation_radius: 0.55

observation_sources: scan 

scan: {sensor_frame: lidar_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
